### ISSUE TITLE
Let's be social

### ISSUE THREAD

**Issue by muan** [muan/ab#4]
Tweet about your high score :zap: :bird:

**Comment by rehman123** [comment]
meet to nice you

**Comment by rehman123** [comment]
m doing programming in java and more excited in making powerful GUI and in back end define a handler that will be called.......
can you help me

**Comment by muan** [comment]
hai nice to meet you too. :wave: I don't know java at all though, so I can't help you :disappointed: good luck though!

**Comment by mrtairus** [comment]
new to github oh i hate being new to anything...but watch how fast i catch up lol!

**Comment by muan** [comment]
:dash:

**Comment by muan** [comment]
![image](https://cloud.githubusercontent.com/assets/1153134/2546489/e38e060e-b638-11e3-8205-cbafa490e985.png)

**Comment by TobiasNickel** [comment]
i needed 7 for 6004
